-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-28 21:21:35 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cliente (
    documento  NUMBER NOT NULL,
    metodopago VARCHAR2(30) NOT NULL,
    cobrototal NUMBER NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( documento );

CREATE TABLE clienteconsumeproducto (
    cliente_documento NUMBER NOT NULL,
    producto_id       NUMBER NOT NULL,
    cantidad          NUMBER
);

ALTER TABLE clienteconsumeproducto ADD CONSTRAINT clienteconsume_pk PRIMARY KEY ( cliente_documento,
                                                                                  producto_id );

CREATE TABLE consumoserviciocliente (
    cliente_documento NUMBER NOT NULL,
    serviciobasico_id NUMBER NOT NULL,
    fecha             DATE NOT NULL,
    descripcion       VARCHAR2(500) NOT NULL
);

ALTER TABLE consumoserviciocliente
    ADD CONSTRAINT consumoserviciocliente_pk PRIMARY KEY ( cliente_documento,
                                                           serviciobasico_id,
                                                           fecha );

CREATE TABLE dotacion (
    tipohabitacion_id NUMBER NOT NULL,
    producto_id       NUMBER NOT NULL
);

ALTER TABLE dotacion ADD CONSTRAINT dotacion_pk PRIMARY KEY ( tipohabitacion_id,
                                                              producto_id );

CREATE TABLE equipossala (
    sala_id     NUMBER NOT NULL,
    producto_id NUMBER NOT NULL
);

ALTER TABLE equipossala ADD CONSTRAINT equipossala_pk PRIMARY KEY ( sala_id,
                                                                    producto_id );

CREATE TABLE gimnasio (
    id    NUMBER NOT NULL,
    costo NUMBER NOT NULL
);

ALTER TABLE gimnasio ADD CONSTRAINT gimnasio_pk PRIMARY KEY ( id );

CREATE TABLE habitacion (
    id                NUMBER NOT NULL,
    disponible        CHAR(1) NOT NULL,
    hotel_id          NUMBER NOT NULL,
    tipohabitacion_id NUMBER NOT NULL
);

ALTER TABLE habitacion ADD CONSTRAINT habitacion_pk PRIMARY KEY ( id );

CREATE TABLE habitacionplan (
    tipohabitacion_id NUMBER NOT NULL,
    plan_id           NUMBER NOT NULL
);

ALTER TABLE habitacionplan ADD CONSTRAINT habitacionplan_pk PRIMARY KEY ( tipohabitacion_id,
                                                                          plan_id );

CREATE TABLE hotel (
    id           NUMBER NOT NULL,
    nombre       VARCHAR2(50) NOT NULL,
    numestrellas NUMBER NOT NULL
);

ALTER TABLE hotel ADD CONSTRAINT hotel_pk PRIMARY KEY ( id );

CREATE TABLE hotelofrece (
    hotel_id          NUMBER NOT NULL,
    serviciobasico_id NUMBER NOT NULL
);

ALTER TABLE hotelofrece ADD CONSTRAINT hotelofrece_pk PRIMARY KEY ( hotel_id,
                                                                    serviciobasico_id );

CREATE TABLE lavanderia (
    id                 NUMBER NOT NULL,
    costoporprenda     NUMBER NOT NULL,
    costoporparzapatos NUMBER NOT NULL
);

ALTER TABLE lavanderia ADD CONSTRAINT lavanderia_pk PRIMARY KEY ( id );

CREATE TABLE maquinasgimnasio (
    gimnasio_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL
);

ALTER TABLE maquinasgimnasio ADD CONSTRAINT maquinasgimnasio_pk PRIMARY KEY ( gimnasio_id,
                                                                              producto_id );

CREATE TABLE piscina (
    id          NUMBER NOT NULL,
    profundidad VARCHAR2(10) NOT NULL,
    costo       NUMBER NOT NULL
);

ALTER TABLE piscina ADD CONSTRAINT piscina_pk PRIMARY KEY ( id );

CREATE TABLE plan (
    id                  NUMBER NOT NULL,
    nombre              VARCHAR2(50) NOT NULL,
    descuentohabitacion NUMBER NOT NULL
);

ALTER TABLE plan ADD CONSTRAINT plan_pk PRIMARY KEY ( id );

CREATE TABLE plato (
    id          NUMBER NOT NULL,
    descripcion VARCHAR2(200) NOT NULL
);

ALTER TABLE plato ADD CONSTRAINT plato_pk PRIMARY KEY ( id );

CREATE TABLE platosrestaurantebar (
    restaurantebar_id NUMBER NOT NULL,
    plato_id          NUMBER NOT NULL
);

ALTER TABLE platosrestaurantebar ADD CONSTRAINT platosrestaurantebar_pk PRIMARY KEY ( restaurantebar_id,
                                                                                      plato_id );

CREATE TABLE prestamo (
    id          NUMBER NOT NULL,
    producto_id NUMBER NOT NULL
);

ALTER TABLE prestamo ADD CONSTRAINT prestamo_pk PRIMARY KEY ( id );

CREATE TABLE producto (
    id                 NUMBER NOT NULL,
    nombre             VARCHAR2(50) NOT NULL,
    precio             NUMBER NOT NULL,
    tipoproducto       VARCHAR2(50) NOT NULL,
    cantidaddisponible NUMBER
);

ALTER TABLE producto ADD CONSTRAINT producto_pk PRIMARY KEY ( id );

CREATE TABLE productoplan (
    producto_id NUMBER NOT NULL,
    plan_id     NUMBER NOT NULL,
    cantidad    NUMBER NOT NULL,
    descripcion VARCHAR2(500) NOT NULL
);

ALTER TABLE productoplan ADD CONSTRAINT productoplan_pk PRIMARY KEY ( producto_id,
                                                                      plan_id );

CREATE TABLE productostienda (
    tienda_id   NUMBER NOT NULL,
    producto_id NUMBER NOT NULL
);

ALTER TABLE productostienda ADD CONSTRAINT productostienda_pk PRIMARY KEY ( tienda_id,
                                                                            producto_id );

CREATE TABLE reservahotel (
    id            NUMBER NOT NULL,
    fechaentrada  DATE NOT NULL,
    fechasalida   DATE NOT NULL,
    numpersonas   NUMBER NOT NULL,
    habitacion_id NUMBER NOT NULL,
    cliente_id    NUMBER NOT NULL,
    plan_id       NUMBER
);

ALTER TABLE reservahotel ADD CONSTRAINT reservahotel_pk PRIMARY KEY ( id );

CREATE TABLE restaurantebar (
    id     NUMBER NOT NULL,
    estilo VARCHAR2(30) NOT NULL
);

ALTER TABLE restaurantebar ADD CONSTRAINT restaurantebar_pk PRIMARY KEY ( id );

CREATE TABLE sala (
    id    NUMBER NOT NULL,
    tipo  VARCHAR2(20) NOT NULL,
    costo NUMBER NOT NULL
);

ALTER TABLE sala ADD CONSTRAINT sala_pk PRIMARY KEY ( id );

CREATE TABLE serviciobasico (
    id        NUMBER NOT NULL,
    nombre    VARCHAR2(30) NOT NULL,
    capacidad NUMBER NOT NULL
);

ALTER TABLE serviciobasico ADD CONSTRAINT serviciobasico_pk PRIMARY KEY ( id );

CREATE TABLE servicioplan (
    plan_id           NUMBER NOT NULL,
    serviciobasico_id NUMBER NOT NULL,
    descuento         NUMBER NOT NULL
);

ALTER TABLE servicioplan ADD CONSTRAINT servicioplan_pk PRIMARY KEY ( plan_id,
                                                                      serviciobasico_id );

CREATE TABLE serviciospa (
    id       NUMBER NOT NULL,
    duracion VARCHAR2(30) NOT NULL
);

ALTER TABLE serviciospa ADD CONSTRAINT serviciospa_pk PRIMARY KEY ( id );

CREATE TABLE serviciosspa (
    spa_id         NUMBER NOT NULL,
    serviciospa_id NUMBER NOT NULL
);

ALTER TABLE serviciosspa ADD CONSTRAINT serviciosspa_pk PRIMARY KEY ( spa_id,
                                                                      serviciospa_id );

CREATE TABLE spa (
    id NUMBER NOT NULL
);

ALTER TABLE spa ADD CONSTRAINT spa_pk PRIMARY KEY ( id );

CREATE TABLE tienda (
    id   NUMBER NOT NULL,
    tipo VARCHAR2(50) NOT NULL
);

ALTER TABLE tienda ADD CONSTRAINT tienda_pk PRIMARY KEY ( id );

CREATE TABLE tipohabitacion (
    id          NUMBER NOT NULL,
    nombre      VARCHAR2(50) NOT NULL,
    capacidad   NUMBER NOT NULL,
    precionoche NUMBER NOT NULL
);

ALTER TABLE tipohabitacion ADD CONSTRAINT tipohabitacion_pk PRIMARY KEY ( id );

CREATE TABLE tipousuario (
    id          NUMBER NOT NULL,
    nombre      VARCHAR2(30) NOT NULL,
    descripcion VARCHAR2(500) NOT NULL
);

ALTER TABLE tipousuario ADD CONSTRAINT tipousuario_pk PRIMARY KEY ( id );

CREATE TABLE usuario (
    documento         NUMBER NOT NULL,
    tipodocumento     VARCHAR2(20) NOT NULL,
    nombre            VARCHAR2(50) NOT NULL,
    correoelectronico VARCHAR2(30) NOT NULL,
    hotel_id          NUMBER NOT NULL,
    tipousuario_id    NUMBER NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT usuario_pk PRIMARY KEY ( documento );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_usuario_fk FOREIGN KEY ( documento )
        REFERENCES usuario ( documento );

ALTER TABLE clienteconsumeproducto
    ADD CONSTRAINT clienteconsume_cliente_fk FOREIGN KEY ( cliente_documento )
        REFERENCES cliente ( documento );

ALTER TABLE clienteconsumeproducto
    ADD CONSTRAINT clienteconsume_producto_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE consumoserviciocliente
    ADD CONSTRAINT consumoserviciocliente_cliente_fk FOREIGN KEY ( cliente_documento )
        REFERENCES cliente ( documento );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE consumoserviciocliente
    ADD CONSTRAINT consumoserviciocliente_serviciobasico_fk FOREIGN KEY ( serviciobasico_id )
        REFERENCES serviciobasico ( id );

ALTER TABLE dotacion
    ADD CONSTRAINT dotacion_producto_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

ALTER TABLE dotacion
    ADD CONSTRAINT dotacion_tipohabitacion_fk FOREIGN KEY ( tipohabitacion_id )
        REFERENCES tipohabitacion ( id );

ALTER TABLE equipossala
    ADD CONSTRAINT equipossala_producto_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

ALTER TABLE equipossala
    ADD CONSTRAINT equipossala_sala_fk FOREIGN KEY ( sala_id )
        REFERENCES sala ( id );

ALTER TABLE gimnasio
    ADD CONSTRAINT gimnasio_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE habitacion
    ADD CONSTRAINT habitacion_hotel_fk FOREIGN KEY ( hotel_id )
        REFERENCES hotel ( id );

ALTER TABLE habitacion
    ADD CONSTRAINT habitacion_tipohabitacion_fk FOREIGN KEY ( tipohabitacion_id )
        REFERENCES tipohabitacion ( id );

ALTER TABLE habitacionplan
    ADD CONSTRAINT habitacionplan_plan_fk FOREIGN KEY ( plan_id )
        REFERENCES plan ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE habitacionplan
    ADD CONSTRAINT habitacionplan_tipohabitacion_fk FOREIGN KEY ( tipohabitacion_id )
        REFERENCES tipohabitacion ( id );

ALTER TABLE hotelofrece
    ADD CONSTRAINT hotelofrece_hotel_fk FOREIGN KEY ( hotel_id )
        REFERENCES hotel ( id );

ALTER TABLE hotelofrece
    ADD CONSTRAINT hotelofrece_serviciobasico_fk FOREIGN KEY ( serviciobasico_id )
        REFERENCES serviciobasico ( id );

ALTER TABLE lavanderia
    ADD CONSTRAINT lavanderia_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE maquinasgimnasio
    ADD CONSTRAINT maquinasgimnasio_gimnasio_fk FOREIGN KEY ( gimnasio_id )
        REFERENCES gimnasio ( id );

ALTER TABLE maquinasgimnasio
    ADD CONSTRAINT maquinasgimnasio_producto_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

ALTER TABLE piscina
    ADD CONSTRAINT piscina_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE plato
    ADD CONSTRAINT plato_producto_fk FOREIGN KEY ( id )
        REFERENCES producto ( id );

ALTER TABLE platosrestaurantebar
    ADD CONSTRAINT platosrestaurantebar_plato_fk FOREIGN KEY ( plato_id )
        REFERENCES plato ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE platosrestaurantebar
    ADD CONSTRAINT platosrestaurantebar_restaurantebar_fk FOREIGN KEY ( restaurantebar_id )
        REFERENCES restaurantebar ( id );

ALTER TABLE prestamo
    ADD CONSTRAINT prestamo_producto_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

ALTER TABLE prestamo
    ADD CONSTRAINT prestamo_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE productoplan
    ADD CONSTRAINT productoplan_plan_id_fk FOREIGN KEY ( plan_id )
        REFERENCES plan ( id );

ALTER TABLE productoplan
    ADD CONSTRAINT productoplan_producto_id_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

ALTER TABLE productostienda
    ADD CONSTRAINT productostienda_producto_fk FOREIGN KEY ( producto_id )
        REFERENCES producto ( id );

ALTER TABLE productostienda
    ADD CONSTRAINT productostienda_tienda_fk FOREIGN KEY ( tienda_id )
        REFERENCES tienda ( id );

ALTER TABLE reservahotel
    ADD CONSTRAINT reservahotel_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( documento );

ALTER TABLE reservahotel
    ADD CONSTRAINT reservahotel_habitacion_fk FOREIGN KEY ( habitacion_id )
        REFERENCES habitacion ( id );

ALTER TABLE reservahotel
    ADD CONSTRAINT reservahotel_plan_fk FOREIGN KEY ( plan_id )
        REFERENCES plan ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE restaurantebar
    ADD CONSTRAINT restaurantebar_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE sala
    ADD CONSTRAINT sala_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE servicioplan
    ADD CONSTRAINT servicioplan_plan_fk FOREIGN KEY ( plan_id )
        REFERENCES plan ( id );

ALTER TABLE servicioplan
    ADD CONSTRAINT servicioplan_serviciobasico_fk FOREIGN KEY ( serviciobasico_id )
        REFERENCES serviciobasico ( id );

ALTER TABLE serviciospa
    ADD CONSTRAINT serviciospa_producto_fk FOREIGN KEY ( id )
        REFERENCES producto ( id );

ALTER TABLE serviciosspa
    ADD CONSTRAINT serviciosspa_serviciospa_fk FOREIGN KEY ( serviciospa_id )
        REFERENCES serviciospa ( id );

ALTER TABLE serviciosspa
    ADD CONSTRAINT serviciosspa_spa_fk FOREIGN KEY ( spa_id )
        REFERENCES spa ( id );

ALTER TABLE spa
    ADD CONSTRAINT spa_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE tienda
    ADD CONSTRAINT tienda_serviciobasico_fk FOREIGN KEY ( id )
        REFERENCES serviciobasico ( id );

ALTER TABLE usuario
    ADD CONSTRAINT usuario_hotel_fk FOREIGN KEY ( hotel_id )
        REFERENCES hotel ( id );

ALTER TABLE usuario
    ADD CONSTRAINT usuario_tipousuario_fk FOREIGN KEY ( tipousuario_id )
        REFERENCES tipousuario ( id );

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            32
-- CREATE INDEX                             0
-- ALTER TABLE                             75
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  15
-- WARNINGS                                 0
